version: '3.8'

services:
  gitpit-app:
    build: .
    container_name: gitpit-production-server
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./data:/usr/src/app/data
